#!/bin/bash


# Write a script that:
# Creates four directories: dir1, dir2, dir3, dir4
#ops-challenge-04


# Put the names of the four directories in an array
# Define array

# paths=(./04directories ./04directories/dir1 ./04directories/dir2 ./04directories/dir3 ./04directories/dir4)
dir_array=(dir1 dir2 dir3 dir4)

# References the array variable to create a new .txt file in each directory
mkdir ${dir_array[@]}

for dir in "${dir_array[@]}"
do
    cd $dir
    touch new.txt
    cd ..
done

# cat ${paths[*]}/new.txt


#create the directories using the paths we put into the array
# mkdir ${paths[*]}




# mkdir ${paths[*]}